<?php
require_once __DIR__ . '/lib/fpdf/fpdf.php';
require_once __DIR__ . '/controller/projectController.php';

$projetC = new ProjetC();
$projects = $projetC->listProjets();
$sponsors = $projetC->listSponsors();

$pdf = new FPDF();
$pdf->AddPage();

/* ===== TITLE ===== */
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'DigiWorkHub',0,1,'C');

$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Liste des Projets et Sponsorships',0,1,'C');
$pdf->Ln(5);

/* ===== PROJECTS ===== */
$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,10,'Liste des Projets',0,1);

/* Table Header */
$pdf->SetFillColor(30,70,140);
$pdf->SetTextColor(255);
$pdf->SetFont('Arial','B',10);

$headers = ['ID','Titre','Budget','Statut'];
$widths = [15, 80, 30, 40];

foreach ($headers as $i => $col) {
    $pdf->Cell($widths[$i],8,$col,1,0,'C',true);
}
$pdf->Ln();

/* Table Data */
$pdf->SetFont('Arial','',9);
$pdf->SetTextColor(0);

foreach ($projects as $p) {
    $pdf->Cell(15,8,$p['id-projet'],1);
    $pdf->Cell(80,8,substr($p['titre'],0,30),1);
    $pdf->Cell(30,8,$p['budget'],1);
    $pdf->Cell(40,8,$p['statut'],1);
    $pdf->Ln();
}

$pdf->Ln(8);

/* ===== SPONSORSHIPS ===== */
$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,10,'Liste des Sponsorships',0,1);

/* Header */
$pdf->SetFillColor(30,70,140);
$pdf->SetTextColor(255);
$pdf->SetFont('Arial','B',10);

$headers2 = ['ID User','Nom','Type'];
$widths2 = [40, 60, 80];

foreach ($headers2 as $i => $col) {
    $pdf->Cell($widths2[$i],8,$col,1,0,'C',true);
}
$pdf->Ln();

/* Data */
$pdf->SetFont('Arial','',9);
$pdf->SetTextColor(0);

foreach ($sponsors as $s) {
    $pdf->Cell(40,8,$s['id_user'],1);
    $pdf->Cell(60,8,substr($s['nom'],0,25),1);
    $pdf->Cell(80,8,substr($s['type'],0,35),1);
    $pdf->Ln();
}

/* ===== FOOTER ===== */
$pdf->Ln(10);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,10,'Generated by DigiWorkHub - '.date('Y-m-d H:i'),0,0,'C');

$pdf->Output();
?>