<?php
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../controller/OffreController.php';

// ── Liste via Controller ─────────────────────────────────────
$controller = new OffreController();
$offres     = $controller->listOffre()->fetchAll(PDO::FETCH_ASSOC);

// ── Message retour ───────────────────────────────────────────
$message     = "";
$messageType = "";
if (isset($_GET['status'], $_GET['msg'])) {
    $messageType = ($_GET['status'] === 'success') ? 'success' : 'danger';
    $message     = htmlspecialchars($_GET['msg']);
}

// Génération de la page en PHP pur
echo '<!DOCTYPE html>';
echo '<html lang="fr">';
echo '<head>';
echo '    <meta charset="UTF-8">';
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '    <title>Liste des offres - DigiWork Hub</title>';
echo '    <link rel="stylesheet" href="assets/css/bootstrap.css">';
echo '    <link rel="stylesheet" href="assets/vendors/perfect-scrollbar/perfect-scrollbar.css">';
echo '    <link rel="stylesheet" href="assets/css/app.css">';
echo '    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">';
echo '    <style>';
echo '        .modal-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.52);z-index:9999;justify-content:center;align-items:center}';
echo '        .modal-overlay.show{display:flex}';
echo '        .modal-box{background:#fff;border-radius:14px;width:100%;max-width:660px;max-height:92vh;overflow-y:auto;box-shadow:0 24px 64px rgba(0,0,0,.25);animation:modalIn .22s ease}';
echo '        @keyframes modalIn{from{transform:translateY(-24px);opacity:0}to{transform:translateY(0);opacity:1}}';
echo '        .modal-top{display:flex;justify-content:space-between;align-items:center;padding:18px 24px 14px;border-bottom:1px solid #f0f1f5}';
echo '        .modal-top h5{margin:0;font-size:16px;font-weight:600;color:#2d3748;display:flex;align-items:center;gap:10px}';
echo '        .icon-edit-wrap{width:34px;height:34px;background:#fff3e0;border-radius:8px;display:flex;align-items:center;justify-content:center}';
echo '        .btn-close-x{background:#f5f6fa;border:none;border-radius:8px;width:32px;height:32px;font-size:18px;cursor:pointer;color:#888;display:flex;align-items:center;justify-content:center;transition:background .15s}';
echo '        .btn-close-x:hover{background:#ffe5e5;color:#e74c3c}';
echo '        .modal-body-inner{padding:20px 24px}';
echo '        .modal-foot{padding:14px 24px;border-top:1px solid #f0f1f5;display:flex;justify-content:flex-end;gap:10px;background:#fafbfc;border-radius:0 0 14px 14px}';
echo '        .btn-edit-orange{background-color:#fd7e14;border:none;color:#fff;border-radius:6px;padding:5px 9px;cursor:pointer;transition:background .15s;display:inline-flex;align-items:center}';
echo '        .btn-edit-orange:hover{background-color:#e86c00}';
echo '        .btn-save-blue{background-color:#435ebe;border:none;color:#fff;border-radius:8px;padding:9px 22px;font-size:14px;font-weight:500;cursor:pointer;display:flex;align-items:center;gap:6px;transition:background .15s}';
echo '        .btn-save-blue:hover{background-color:#3348a8}';
echo '        .btn-cancel-modal{background:#f5f6fa;border:none;color:#666;border-radius:8px;padding:9px 20px;font-size:14px;cursor:pointer;transition:background .15s}';
echo '        .btn-cancel-modal:hover{background:#e8e9ef}';
echo '        .field-label{font-size:12px;font-weight:600;color:#6c757d;text-transform:uppercase;letter-spacing:.04em;margin-bottom:5px;display:block}';
echo '        .form-control{font-size:14px;border-radius:8px}';
echo '        .form-control:focus{border-color:#435ebe;box-shadow:0 0 0 3px rgba(67,94,190,.12)}';
echo '        .section-divider{font-size:11px;font-weight:700;color:#adb5bd;text-transform:uppercase;letter-spacing:.08em;margin:4px 0 14px;display:flex;align-items:center;gap:8px}';
echo '        .section-divider::after{content:\'\';flex:1;height:1px;background:#f0f1f5}';
echo '    </style>';
echo '</head>';
echo '<body>';
echo '<div id="app">';

// SIDEBAR
echo '    <aside id="sidebar" class="active">';
echo '        <div class="sidebar-wrapper active">';
echo '            <div class="sidebar-header"><img src="assets/images/logo.png" style="width:230px;"></div>';
echo '            <div class="sidebar-menu">';
echo '                <ul class="menu">';
echo '                    <li class="sidebar-title">Menu Principal</li>';
echo '                    <li class="sidebar-item">';
echo '                        <a href="index.php" class="sidebar-link"><i data-feather="home" width="20"></i><span>Dashboard</span></a>';
echo '                    </li>';
echo '                    <li class="sidebar-title">Gestion</li>';
echo '                    <li class="sidebar-item active has-sub">';
echo '                        <a href="#" class="sidebar-link"><i data-feather="tag" width="20"></i><span>Gestion des offres</span></a>';
echo '                        <ul class="submenu open">';
echo '                            <li><a href="listOffres.php" class="active">Toutes les offres</a></li>';
echo '                            <li><a href="addOffre.php">Ajouter une offre</a></li>';
echo '                            <li><a href="offresExpirees.php">Offres expirées</a></li>';
echo '                        </ul>';
echo '                    </li>';
echo '                    <li class="sidebar-item has-sub">';
echo '                        <a href="#" class="sidebar-link"><i data-feather="users" width="20"></i><span>Gestion des utilisateurs</span></a>';
echo '                        <ul class="submenu">';
echo '                            <li><a href="listUsers.php">Tous les utilisateurs</a></li>';
echo '                            <li><a href="addUser.php">Ajouter un utilisateur</a></li>';
echo '                            <li><a href="rolesPermissions.php">Rôles &amp; permissions</a></li>';
echo '                        </ul>';
echo '                    </li>';
echo '                    <li class="sidebar-item has-sub">';
echo '                        <a href="#" class="sidebar-link"><i data-feather="message-square" width="20"></i><span>Gestion des forums</span></a>';
echo '                        <ul class="submenu">';
echo '                            <li><a href="listForums.php">Tous les forums</a></li>';
echo '                            <li><a href="categoriesForums.php">Catégories</a></li>';
echo '                            <li><a href="signalements.php">Signalements</a></li>';
echo '                        </ul>';
echo '                    </li>';
echo '                    <li class="sidebar-item has-sub">';
echo '                        <a href="#" class="sidebar-link"><i data-feather="folder" width="20"></i><span>Gestion des projets</span></a>';
echo '                        <ul class="submenu">';
echo '                            <li><a href="listProjets.php">Tous les projets</a></li>';
echo '                            <li><a href="addProjet.php">Ajouter un projet</a></li>';
echo '                            <li><a href="projetsArchives.php">Archivés</a></li>';
echo '                        </ul>';
echo '                    </li>';
echo '                </ul>';
echo '            </div>';
echo '            <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>';
echo '        </div>';
echo '    </aside>';

// MAIN
echo '    <main id="main">';
echo '        <nav class="navbar navbar-header navbar-expand navbar-light">';
echo '            <a class="sidebar-toggler" href="#"><span class="navbar-toggler-icon"></span></a>';
echo '            <div class="collapse navbar-collapse">';
echo '                <ul class="navbar-nav d-flex align-items-center navbar-light ml-auto">';
echo '                    <li class="dropdown">';
echo '                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">';
echo '                            <div class="avatar mr-1"><img src="assets/images/avatar/avatar-s-1.png" alt=""></div>';
echo '                            <div class="d-none d-md-block d-lg-inline-block">Admin</div>';
echo '                        </a>';
echo '                        <div class="dropdown-menu dropdown-menu-right">';
echo '                            <a class="dropdown-item" href="#"><i data-feather="user"></i> Compte</a>';
echo '                            <a class="dropdown-item" href="#"><i data-feather="settings"></i> Paramètres</a>';
echo '                            <div class="dropdown-divider"></div>';
echo '                            <a class="dropdown-item" href="#"><i data-feather="log-out"></i> Déconnexion</a>';
echo '                        </div>';
echo '                    </li>';
echo '                </ul>';
echo '            </div>';
echo '        </nav>';

echo '        <section class="main-content container-fluid">';
echo '            <header class="page-title">';
echo '                <div class="row">';
echo '                    <div class="col-12 col-md-6 order-md-1 order-last">';
echo '                        <h3>Liste des offres</h3>';
echo '                        <p class="text-subtitle text-muted">Gérer toutes les offres disponibles</p>';
echo '                    </div>';
echo '                    <div class="col-12 col-md-6 order-md-2 order-first">';
echo '                        <nav aria-label="breadcrumb" class="breadcrumb-header float-right float-lg-right">';
echo '                            <ol class="breadcrumb">';
echo '                                <li class="breadcrumb-item"><a href="index.php">Dashboard</a></li>';
echo '                                <li class="breadcrumb-item active">Liste des offres</li>';
echo '                            </ol>';
echo '                        </nav>';
echo '                    </div>';
echo '                </div>';
echo '            </header>';

echo '            <section class="section">';

if ($message !== ""):
    echo '                <div class="alert alert-' . $messageType . ' alert-dismissible fade show" role="alert">';
    echo '                    ' . ($messageType === 'success' ? '✅' : '❌') . ' ' . $message;
    echo '                    <button type="button" class="close" data-dismiss="alert">&times;</button>';
    echo '                </div>';
endif;

echo '                <div class="card">';
echo '                    <div class="card-header d-flex justify-content-between align-items-center">';
echo '                        <h4 class="card-title">Toutes les offres</h4>';
echo '                        <button class="btn btn-primary" onclick="openAddModal()">';
echo '                            <i data-feather="plus" width="16"></i> Ajouter une offre';
echo '                        </button>';
echo '                    </div>';
echo '                    <div class="card-body px-0 pb-0">';
echo '                        <div class="table-responsive">';
echo '                            <table class="table table-hover mb-0">';
echo '                                <thead>';
echo '                                    <tr>';
echo '                                        <th>#</th><th>Titre</th><th>Description</th>';
echo '                                        <th>Compétences</th><th>Date limite</th>';
echo '                                        <th>Adresse</th><th>Type</th><th>Entreprise</th><th>Actions</th>';
echo '                                    </tr>';
echo '                                </thead>';
echo '                                <tbody>';

if (count($offres) > 0):
    foreach ($offres as $o):
        echo '                                    <tr>';
        echo '                                        <td>' . htmlspecialchars($o['id_offer']) . '</td>';
        echo '                                        <td><strong>' . htmlspecialchars($o['titre']) . '</strong></td>';
        echo '                                        <td style="max-width:160px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">';
        echo '                                            ' . htmlspecialchars($o['description']);
        echo '                                        </td>';
        echo '                                        <td><span class="badge bg-info">' . htmlspecialchars($o['competences']) . '</span></td>';
        echo '                                        <td>' . htmlspecialchars($o['date_limite']) . '</td>';
        echo '                                        <td>' . htmlspecialchars($o['adresse']) . '</td>';
        echo '                                        <td><span class="badge bg-primary">' . htmlspecialchars($o['type']) . '</span></td>';
        echo '                                        <td>' . htmlspecialchars($o['id_entreprise']) . '</td>';
        echo '                                        <td style="white-space:nowrap">';
        echo '                                            <button class="btn-edit-orange"';
        echo '                                                data-id="' . $o['id_offer'] . '"';
        echo '                                                data-titre="' . htmlspecialchars($o['titre'], ENT_QUOTES) . '"';
        echo '                                                data-description="' . htmlspecialchars($o['description'], ENT_QUOTES) . '"';
        echo '                                                data-competences="' . htmlspecialchars($o['competences'], ENT_QUOTES) . '"';
        echo '                                                data-date="' . htmlspecialchars($o['date_limite'], ENT_QUOTES) . '"';
        echo '                                                data-adresse="' . htmlspecialchars($o['adresse'], ENT_QUOTES) . '"';
        echo '                                                data-type="' . htmlspecialchars($o['type'], ENT_QUOTES) . '"';
        echo '                                                data-entreprise="' . htmlspecialchars($o['id_entreprise'], ENT_QUOTES) . '"';
        echo '                                                onclick="openEditModal(this)">';
        echo '                                                <i data-feather="edit-2" width="14"></i>';
        echo '                                            </button>';
        echo '                                            <button class="btn btn-sm btn-danger ml-1"';
        echo '                                                data-id="' . $o['id_offer'] . '"';
        echo '                                                data-titre="' . htmlspecialchars($o['titre'], ENT_QUOTES) . '"';
        echo '                                                onclick="openDeleteModal(this)">';
        echo '                                                <i data-feather="trash-2" width="14"></i>';
        echo '                                            </button>';
        echo '                                        </td>';
        echo '                                     </tr>';
    endforeach;
else:
    echo '                                    <tr>';
    echo '                                        <td colspan="9" class="text-center text-muted py-5">';
    echo '                                            <i data-feather="inbox" width="32"></i>';
    echo '                                            <p class="mt-2">Aucune offre disponible.</p>';
    echo '                                        </td>';
    echo '                                     </tr>';
endif;

echo '                                </tbody>';
echo '                            </table>';
echo '                        </div>';
echo '                    </div>';
echo '                </div>';
echo '            </section>';
echo '        </section>';
echo '    </main>';
echo '</div>';

// MODALE MODIFIER
echo '<div class="modal-overlay" id="editModal">';
echo '    <div class="modal-box">';
echo '        <div class="modal-top">';
echo '            <h5>';
echo '                <div class="icon-edit-wrap">';
echo '                    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#fd7e14" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">';
echo '                        <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>';
echo '                        <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>';
echo '                    </svg>';
echo '                </div>';
echo '                Modifier l\'offre';
echo '            </h5>';
echo '            <button class="btn-close-x" onclick="closeEditModal()">&#x2715;</button>';
echo '        </div>';
echo '        <form method="POST" action="updateOffre.php">';
echo '            <input type="hidden" name="id_offer" id="modal_id">';
echo '            <div class="modal-body-inner">';
echo '                <div class="section-divider">Informations principales</div>';
echo '                <div class="form-group">';
echo '                    <label class="field-label">Titre <span class="text-danger">*</span></label>';
echo '                    <input type="text" class="form-control" name="titre" id="modal_titre" required>';
echo '                </div>';
echo '                <div class="form-group">';
echo '                    <label class="field-label">Description <span class="text-danger">*</span></label>';
echo '                    <textarea class="form-control" name="description" id="modal_description" rows="3" required></textarea>';
echo '                </div>';
echo '                <div class="form-group">';
echo '                    <label class="field-label">Compétences <span class="text-danger">*</span></label>';
echo '                    <input type="text" class="form-control" name="competences" id="modal_competences" required>';
echo '                </div>';
echo '                <div class="section-divider">Détails du contrat</div>';
echo '                <div class="row">';
echo '                    <div class="col-md-6">';
echo '                        <div class="form-group">';
echo '                            <label class="field-label">Date limite <span class="text-danger">*</span></label>';
echo '                            <input type="date" class="form-control" name="date_limite" id="modal_date_limite" required>';
echo '                        </div>';
echo '                    </div>';
echo '                    <div class="col-md-6">';
echo '                        <div class="form-group">';
echo '                            <label class="field-label">Type de contrat <span class="text-danger">*</span></label>';
echo '                            <select class="form-control" name="type" id="modal_type" required>';
echo '                                <option value="CDI">CDI</option>';
echo '                                <option value="CDD">CDD</option>';
echo '                                <option value="Stage">Stage</option>';
echo '                                <option value="Freelance">Freelance</option>';
echo '                                <option value="Alternance">Alternance</option>';
echo '                            </select>';
echo '                        </div>';
echo '                    </div>';
echo '                </div>';
echo '                <div class="row">';
echo '                    <div class="col-md-8">';
echo '                        <div class="form-group">';
echo '                            <label class="field-label">Adresse <span class="text-danger">*</span></label>';
echo '                            <input type="text" class="form-control" name="adresse" id="modal_adresse" required>';
echo '                        </div>';
echo '                    </div>';
echo '                    <div class="col-md-4">';
echo '                        <div class="form-group">';
echo '                            <label class="field-label">ID Entreprise <span class="text-danger">*</span></label>';
echo '                            <input type="number" class="form-control" name="id_entreprise" id="modal_id_entreprise" required>';
echo '                        </div>';
echo '                    </div>';
echo '                </div>';
echo '            </div>';
echo '            <div class="modal-foot">';
echo '                <button type="button" class="btn-cancel-modal" onclick="closeEditModal()">Annuler</button>';
echo '                <button type="submit" class="btn-save-blue">';
echo '                    <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">';
echo '                        <path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/>';
echo '                        <polyline points="17 21 17 13 7 13 7 21"/>';
echo '                        <polyline points="7 3 7 8 15 8"/>';
echo '                    </svg>';
echo '                    Enregistrer les modifications';
echo '                </button>';
echo '            </div>';
echo '        </form>';
echo '    </div>';
echo '</div>';

// MODALE SUPPRIMER
echo '<div class="modal-overlay" id="deleteModal">';
echo '    <div class="modal-box" style="max-width:440px">';
echo '        <div class="modal-top">';
echo '            <h5>';
echo '                <div class="icon-edit-wrap" style="background:#ffe5e5">';
echo '                    <svg xmlns="http://www.w3.org/2000/svg" width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="#dc3545" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">';
echo '                        <polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>';
echo '                        <path d="M10 11v6"/><path d="M14 11v6"/>';
echo '                        <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>';
echo '                    </svg>';
echo '                </div>';
echo '                Confirmer la suppression';
echo '            </h5>';
echo '            <button class="btn-close-x" onclick="closeDeleteModal()">&#x2715;</button>';
echo '        </div>';
echo '        <div class="modal-body-inner" style="text-align:center;padding:28px 24px">';
echo '            <div style="width:64px;height:64px;background:#ffe5e5;border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 16px">';
echo '                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="#dc3545" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">';
echo '                    <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>';
echo '                </svg>';
echo '            </div>';
echo '            <h6 style="font-size:16px;font-weight:600;color:#2d3748;margin-bottom:8px">Êtes-vous sûr ?</h6>';
echo '            <p style="color:#6c757d;font-size:14px;margin-bottom:4px">Vous allez supprimer l\'offre :</p>';
echo '            <p id="delete-titre" style="font-weight:600;color:#dc3545;font-size:14px;margin-bottom:0"></p>';
echo '            <p style="color:#adb5bd;font-size:12px;margin-top:8px">Cette action est irréversible.</p>';
echo '        </div>';
echo '        <div class="modal-foot" style="justify-content:center;gap:12px">';
echo '            <button type="button" class="btn-cancel-modal" onclick="closeDeleteModal()" style="padding:10px 28px">Annuler</button>';
echo '            <a id="delete-confirm-btn" href="#"';
echo '               style="background:#dc3545;color:#fff;border-radius:8px;padding:10px 28px;font-size:14px;font-weight:500;display:flex;align-items:center;gap:6px;text-decoration:none;transition:background .15s"';
echo '               onmouseover="this.style.background=\'#b02a37\'" onmouseout="this.style.background=\'#dc3545\'">';
echo '                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round">';
echo '                    <polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>';
echo '                    <path d="M10 11v6"/><path d="M14 11v6"/>';
echo '                    <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>';
echo '                </svg>';
echo '                Oui, supprimer';
echo '            </a>';
echo '        </div>';
echo '    </div>';
echo '</div>';

echo '<script src="assets/js/feather-icons/feather.min.js"></script>';
echo '<script src="assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>';
echo '<script src="assets/js/app.js"></script>';
echo '<script src="assets/js/main.js"></script>';
echo '<script>';
echo 'feather.replace();';
echo ' ';
echo 'function openAddModal(){ document.getElementById(\'addModal\').classList.add(\'show\'); document.body.style.overflow=\'hidden\'; }';
echo 'function closeAddModal(){ document.getElementById(\'addModal\').classList.remove(\'show\'); document.body.style.overflow=\'\'; }';
echo ' ';
echo 'function openEditModal(btn){';
echo '    document.getElementById(\'modal_id\').value            = btn.getAttribute(\'data-id\');';
echo '    document.getElementById(\'modal_titre\').value         = btn.getAttribute(\'data-titre\');';
echo '    document.getElementById(\'modal_description\').value   = btn.getAttribute(\'data-description\');';
echo '    document.getElementById(\'modal_competences\').value   = btn.getAttribute(\'data-competences\');';
echo '    document.getElementById(\'modal_date_limite\').value   = btn.getAttribute(\'data-date\');';
echo '    document.getElementById(\'modal_adresse\').value       = btn.getAttribute(\'data-adresse\');';
echo '    document.getElementById(\'modal_id_entreprise\').value = btn.getAttribute(\'data-entreprise\');';
echo '    var type=btn.getAttribute(\'data-type\'), sel=document.getElementById(\'modal_type\');';
echo '    for(var i=0;i<sel.options.length;i++){ if(sel.options[i].value===type){sel.selectedIndex=i;break;} }';
echo '    document.getElementById(\'editModal\').classList.add(\'show\');';
echo '    document.body.style.overflow=\'hidden\';';
echo '}';
echo 'function closeEditModal(){ document.getElementById(\'editModal\').classList.remove(\'show\'); document.body.style.overflow=\'\'; }';
echo 'document.getElementById(\'editModal\').addEventListener(\'click\',function(e){ if(e.target===this)closeEditModal(); });';
echo ' ';
echo 'function openDeleteModal(btn){';
echo '    document.getElementById(\'delete-titre\').textContent = btn.getAttribute(\'data-titre\');';
echo '    document.getElementById(\'delete-confirm-btn\').href  = \'deleteOffre.php?id=\'+btn.getAttribute(\'data-id\');';
echo '    document.getElementById(\'deleteModal\').classList.add(\'show\');';
echo '    document.body.style.overflow=\'hidden\';';
echo '}';
echo 'function closeDeleteModal(){ document.getElementById(\'deleteModal\').classList.remove(\'show\'); document.body.style.overflow=\'\'; }';
echo 'document.getElementById(\'deleteModal\').addEventListener(\'click\',function(e){ if(e.target===this)closeDeleteModal(); });';
echo ' ';
echo 'document.addEventListener(\'keydown\',function(e){';
echo '    if(e.key===\'Escape\'){closeEditModal();closeDeleteModal();}';
echo '});';
echo '</script>';
echo '</body>';
echo '</html>';
?>